[[redirects]]
  from = "/pact_broker/terraform-provider"
  to = "/pact_broker/terraform_provider"
  status = 301

[[redirects]]
  from = "/pact_broker/advanced_topics/webhooks/template_lib"
  to = "/pact_broker/webhooks/template_library"
  status = 301

[[redirects]]
  from = "/pact_broker/advanced_topics/webhooks"
  to = "/pact_broker/webhooks"
  status = 301

[[redirects]]
  from = "/consumer_version_selectors"
  to = "/pact_broker/advanced_topics/consumer_version_selectors"
  status = 301

[[redirects]]
  from = "/pending"
  to = "/pact_broker/advanced_topics/pending_pacts"
  status = 301

[[redirects]]
  from = "/wip"
  to = "/pact_broker/advanced_topics/wip_pacts"
  status = 301

[[redirects]]
  from = "/can_i_deploy"
  to = "/pact_broker/can_i_deploy"
  status = 301

[[redirects]]
  from = "/pact_broker/pact_broker_client_cli"
  to = "/pact_broker/client_cli"
  status = 301

[[redirects]]
  from = "/guides"
  to = "/consumer"
  status = 302

[[redirects]]
  from = "/workshops"
  to = "/implementation_guides/workshops"
  status = 302

[[redirects]]
  from = "/implementation_guides"
  to = "/implementation_guides/cli"
  status = 302

[[redirects]]
  from = "/pact_broker/advanced_topics/provider_verification_results"
  to = "/pact_broker/provider_verification_results"
  status = 302

[[redirects]]
  from = "/getting_started"
  to = "/"
  status = 302
